# Base Image (Node 20 con Alpine para ser más ligero)
FROM node:20-alpine AS build

# Directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar archivos de configuración para instalar dependencias
COPY package.json yarn.lock ./

# Instalar dependencias utilizando Yarn
RUN yarn

# Copiar todo el proyecto al contenedor
COPY . .

# Exponer el puerto en el que la aplicación correrá
EXPOSE 3000

# Comando para correr la aplicación
CMD ["yarn", "run", "start-watch"]