version: '3.8'

services:
  frontend:
    image: seek-front
    stdin_open: true
    ports:
      "3000:3000"

    volumes:
      - "./:/usr/src/app:delegated"
      - /usr/src/app/nodel_modules/
    